Repository STEM-C/CaSMM, pull requests merged in 2021-07, with the labels that each got.

#223 fix #222: filter unable to process unit number > 9
  client/src/views/Classroom/Home/LearningStandardSelect/CheckUnits.js
Labels: bug, frontend

#229 fix bug where mentor/cc not able to upload code to arduino
  client/src/components/DayPanels/helpers.js
Labels: bug

#228 Feature/student_login_auth
  client/src/views/StudentLogin/StudentLogin.js
  client/src/views/StudentLogin/StudentLogin.less
  client/src/views/StudentLogin/StudentLoginForm.js
Labels: enhancement, frontend

#232 fixed update unit for cc
  client/src/Utils/requests.js
  client/src/views/ContentCreator/UnitEditor/UnitEditor.js
Labels: bug

#235 Bug/toolbox update
  client/src/components/DayPanels/BlocklyCanvasPanel/BlocklyCanvasPanel.js
  client/src/views/ContentCreator/LearningStandardDayCreator/DayEditor.js
Labels: bug

#221 Feature/console view
  client/package.json
  client/public/lib/avrgirl-arduino.global.js
  client/src/assets/style.less
  client/src/components/DayPanels/BlocklyCanvasPanel/BlocklyCanvasPanel.js
  client/src/components/DayPanels/BlocklyCanvasPanel/ConsoleModal.js
  client/src/components/DayPanels/ConsoleView.js
  client/src/components/DayPanels/DayPanels.less
  client/src/components/DayPanels/helpers.js
  client/src/components/MentorSubHeader/MentorSubHeader.less
  client/src/components/Message.js
  client/src/views/ContentCreator/ContentCreator.js
  client/src/views/ContentCreator/ContentCreator.less
  client/src/views/ContentCreator/LearningStandardCreator/LearningStandardCreator.js
  client/src/views/ContentCreator/LearningStandardCreator/LearningStandardCreator.less
  client/src/views/ContentCreator/LearningStandardDayCreator/DayEditor.js
  client/src/views/ContentCreator/UnitCreator/UnitCreator.js
  client/src/views/ContentCreator/UnitCreator/UnitCreator.less
  client/src/views/ContentCreator/UnitEditor/UnitEditor.js
  client/src/views/Dashboard/Dashboard.js
  server/yarn.lock
Labels: enhancement, frontend
